CREATE OR REPLACE FUNCTION UTL_SEQ_NEXTVAL_FIELD(NOME_TAB IN VARCHAR2, NOME_FIELD IN VARCHAR2) RETURN NUMBER IS
  RET_NEXTVAL NUMBER;
  SEQ_NAME VARCHAR2(30);
  
  EX_SEQ_NEX_VAL_ERR EXCEPTION;
  PRAGMA EXCEPTION_INIT(EX_SEQ_NEX_VAL_ERR, -20999);
BEGIN
  
  SELECT NOME_SEQUENZA
  INTO SEQ_NAME
  FROM UTL_SEQUENCE_FACILITY 
  WHERE NOME_TABELLA = NOME_TAB
    AND NOME_CAMPO = NOME_FIELD;
  
  IF SEQ_NAME = '-' THEN
    EXECUTE IMMEDIATE 'SELECT MAX('||NOME_FIELD||')+1 FROM '||NOME_TAB  INTO RET_NEXTVAL;
    RETURN RET_NEXTVAL;
  ELSE
    EXECUTE IMMEDIATE 'SELECT '||SEQ_NAME||'.NEXTVAL FROM DUAL' INTO RET_NEXTVAL;
    RETURN RET_NEXTVAL;
  END IF;
  
  EXCEPTION
    WHEN OTHERS THEN
      RAISE_APPLICATION_ERROR( -20999, 'UTL_SEQ_NEXTVAL_FIELD - ERRORE:'||SQLERRM);
END;
/