CREATE OR REPLACE FUNCTION UTL_SEQ_NEXTVAL(NOME_TAB IN VARCHAR2) RETURN NUMBER IS
  RET_NEXTVAL NUMBER;
  SEQ_NAME VARCHAR2(30);
  SEQ_FIELD VARCHAR2(30);
  
  EX_SEQ_NEX_VAL_ERR EXCEPTION;
  PRAGMA EXCEPTION_INIT(EX_SEQ_NEX_VAL_ERR, -20999);
BEGIN
  
  SELECT NOME_SEQUENZA, NOME_CAMPO INTO SEQ_NAME, SEQ_FIELD FROM UTL_SEQUENCE_FACILITY WHERE NOME_TABELLA = NOME_TAB;
  
  IF SEQ_NAME = '-' THEN
    EXECUTE IMMEDIATE 'SELECT MAX('||SEQ_FIELD||')+1 FROM '||NOME_TAB  INTO RET_NEXTVAL;
    RETURN RET_NEXTVAL;
  ELSE
    EXECUTE IMMEDIATE 'SELECT '||SEQ_NAME||'.NEXTVAL FROM DUAL' INTO RET_NEXTVAL;
    RETURN RET_NEXTVAL;
  END IF;
    
  EXCEPTION
    WHEN TOO_MANY_ROWS THEN
      RAISE_APPLICATION_ERROR( -20999, 'UTL_SEQ_NEXTVAL - Troppe sequences per '||NOME_TAB||' - Usare UTL_SEQ_NEXTVAL_FIELD e specificare il campo.' );
    WHEN OTHERS THEN
      RAISE_APPLICATION_ERROR( -20999, 'UTL_SEQ_NEXTVAL - ERRORE:'||SQLERRM);
END;
/