CREATE TABLE UTL_SEQUENCE_FACILITY (
  NOME_TABELLA  VARCHAR2(30),
  NOME_CAMPO    VARCHAR2(30),
  NOME_SEQUENZA VARCHAR2(30)
);
CREATE UNIQUE INDEX IX_UTL_SEQFAL ON UTL_SEQUENCE_FACILITY(NOME_TABELLA, NOME_CAMPO, NOME_SEQUENZA);