
CREATE OR REPLACE PACKAGE BODY PKG_CURSORI AS

	PROCEDURE CURSORE (cursoreOut OUT SYS_REFCURSOR) IS
	BEGIN
		OPEN cursoreOut FOR SELECT SYSDATE AS OGGI FROM DUAL;
	END CURSORE;

	PROCEDURE CHIAMA_CUR IS
		cur1 SYS_REFCURSOR;
		--elenco field in cui fetchare oppure
		tab1 TABELLA%ROWTYPE;
	BEGIN
		CURSORE(cur1);
		LOOP
			FETCH cur1
			INTO tab1;
			EXIT WHEN cur1%NOTFOUND;
			--do something
			DBMS_OUTPUT.PUT_LINE(tab1.OGGI);
		END LOOP;
		CLOSE cur1;
	END CHIAMA_CUR;
END;