create or replace PACKAGE PKG_LOGS AS
  --Settings--------------------------------------------------------------------
  LOG_DESTINATION   VARCHAR2(10)    := 'FILE'; --Enum: FILE, DB, COMBO
  ORIGIN            VARCHAR2(30)    := 'UNKNOWN';
  CARTELLA_LOG      VARCHAR2(200)   := 'LOGDIR';
  FILE_LOG          VARCHAR2(200)   := 'default_log_file.log';
  GUID              VARCHAR2(200)   := SYS_GUID();
  INFO_ENABLED      VARCHAR2(10)    := 'TRUE';
  ERROR_ENABLED     VARCHAR2(10)    := 'TRUE';
  WARN_ENABLED      VARCHAR2(10)    := 'TRUE';
  DEBUG_ENABLED     VARCHAR2(10)    := 'FALSE';
  --Procedures------------------------------------------------------------------
  ----Initialization
  PROCEDURE LOG_INIT(ORIGIN_IN IN VARCHAR2, CARTELLA_IN IN VARCHAR2, FILE_IN IN VARCHAR2, GUID_IN IN VARCHAR2);
  PROCEDURE CONFIG_LOG_DESTINATION(LOG_DESTINATION_IN IN VARCHAR2 DEFAULT 'FILE');
  ----Specialized
  PROCEDURE LOG_WARN(MODULE IN VARCHAR2, MESSAGE IN VARCHAR2);
  PROCEDURE LOG_INFO(MODULE IN VARCHAR2, MESSAGE IN VARCHAR2);
  PROCEDURE LOG_ERROR(MODULE IN VARCHAR2, MESSAGE IN VARCHAR2, STACKTRACE IN VARCHAR2);
  PROCEDURE LOG_DEBUG(MODULE IN VARCHAR2, MESSAGE IN VARCHAR2);
----Utils
  FUNCTION DATAFY(FILE_NAME IN VARCHAR2) RETURN VARCHAR2;
END PKG_LOGS;
/